import type { PreScreenQuestionConfig, PreScreenQuestionId } from "./question-types";

export const PRE_SCREEN_QUESTION_CONFIGS: PreScreenQuestionConfig[] = [
  {
    id: "profile_name",
    stepId: "profile_name",
    section: "profile",
    field: "profile_name",
    inputType: "text",
    title: "Your full name",
    prompt: "What is your full name?",
    placeholder: "Enter your full name",
    showInReview: true,
    agentContextLabel: "student_name",
  },
  {
    id: "profile_college",
    stepId: "profile_college",
    section: "profile",
    field: "profile_college",
    inputType: "text",
    title: "Your college",
    prompt: "Which college or institution are you studying in?",
    placeholder: "Enter your college name",
    showInReview: true,
    agentContextLabel: "college",
  },
  {
    id: "profile_degree",
    stepId: "profile_degree",
    section: "profile",
    field: "profile_degree",
    inputType: "text",
    title: "Your degree",
    prompt: "What degree are you pursuing?",
    placeholder: "Example: B.Tech, B.Com, MBA",
    showInReview: true,
    agentContextLabel: "degree",
  },
  {
    id: "profile_stream",
    stepId: "profile_stream",
    section: "profile",
    field: "profile_stream",
    inputType: "text",
    title: "Your stream",
    prompt: "What is your stream / branch / specialization?",
    placeholder: "Example: CSE, Mechanical, Finance",
    showInReview: true,
    agentContextLabel: "stream",
  },
  {
    id: "profile_year",
    stepId: "profile_year",
    section: "profile",
    field: "profile_year",
    inputType: "text",
    title: "Year of study",
    prompt: "Which year of study are you currently in?",
    placeholder: "Example: 3rd year",
    showInReview: true,
    agentContextLabel: "year_of_study",
  },
  {
    id: "job_aiming_role",
    stepId: "job_aiming_role",
    section: "job_plans",
    field: "job_aiming_role",
    inputType: "text",
    title: "Main target role",
    prompt: "What job role are you mainly aiming for right now?",
    placeholder: "Example: Software Engineer",
    showInReview: true,
    agentContextLabel: "aiming_role",
  },
  {
    id: "job_dream_role",
    stepId: "job_dream_role",
    section: "job_plans",
    field: "job_dream_role",
    inputType: "text",
    title: "Dream role",
    prompt: "What is your dream job or dream role?",
    placeholder: "Enter your dream role",
    showInReview: true,
    agentContextLabel: "dream_role",
  },
  {
    id: "job_backup_role",
    stepId: "job_backup_role",
    section: "job_plans",
    field: "job_backup_role",
    inputType: "text",
    title: "Backup role",
    prompt: "What backup role would you be willing to take first?",
    placeholder: "Enter your backup role",
    showInReview: true,
    agentContextLabel: "backup_role",
  },
  {
    id: "job_why_aiming",
    stepId: "job_why_aiming",
    section: "job_plans",
    field: "job_why_aiming",
    inputType: "textarea",
    title: "Why this role",
    prompt: "Why are you aiming for this main role?",
    placeholder: "Tell us why this role fits you",
    showInReview: true,
    agentContextLabel: "why_aiming_role",
  },
  {
    id: "job_why_dream",
    stepId: "job_why_dream",
    section: "job_plans",
    field: "job_why_dream",
    inputType: "textarea",
    title: "Why dream role",
    prompt: "Why is your dream role important to you?",
    placeholder: "Tell us why this role matters to you",
    showInReview: true,
    agentContextLabel: "why_dream_role",
  },
  {
    id: "job_why_backup",
    stepId: "job_why_backup",
    section: "job_plans",
    field: "job_why_backup",
    inputType: "textarea",
    title: "Why backup role",
    prompt: "Why did you choose this backup role?",
    placeholder: "Explain why this is your backup plan",
    showInReview: true,
    agentContextLabel: "why_backup_role",
  },
  {
    id: "research_companies",
    stepId: "research_companies",
    section: "job_research",
    field: "research_companies",
    inputType: "textarea",
    title: "Campus companies",
    prompt: "Which companies usually visit your campus for these roles?",
    placeholder: "List the companies you know",
    showInReview: true,
    agentContextLabel: "campus_companies",
  },
  {
    id: "research_seniors",
    stepId: "research_seniors",
    section: "job_research",
    field: "research_seniors",
    inputType: "textarea",
    title: "Placed seniors",
    prompt: "Do you know any seniors or alumni who got placed in these roles? If yes, where?",
    placeholder: "Share any placement examples you know",
    showInReview: true,
    agentContextLabel: "known_placed_seniors",
  },
  {
    id: "research_skills_tools",
    stepId: "research_skills_tools",
    section: "job_research",
    field: "research_skills_tools",
    inputType: "textarea",
    title: "Expected skills",
    prompt: "What skills or tools do companies expect for your target role?",
    placeholder: "Example: SQL, Excel, DSA, Figma",
    showInReview: true,
    agentContextLabel: "expected_skills_tools",
  },
  {
    id: "research_role_responsibilities",
    stepId: "research_role_responsibilities",
    section: "job_research",
    field: "research_role_responsibilities",
    inputType: "textarea",
    title: "Role responsibilities",
    prompt: "What do you think are the main responsibilities in this role?",
    placeholder: "Describe what someone in this role does",
    showInReview: true,
    agentContextLabel: "role_responsibilities",
  },
  {
    id: "research_salary_awareness",
    stepId: "research_salary_awareness",
    section: "job_research",
    field: "research_salary_awareness",
    inputType: "textarea",
    title: "Salary awareness",
    prompt: "What salary range do you think freshers in this role usually get?",
    placeholder: "Share the range you know",
    showInReview: true,
    agentContextLabel: "salary_awareness",
  },
  {
    id: "research_jd_awareness",
    stepId: "research_jd_awareness",
    section: "job_research",
    field: "research_jd_awareness",
    inputType: "textarea",
    title: "JD awareness",
    prompt: "Have you seen a job description for this role? What do you remember from it?",
    placeholder: "Summarize what you remember from a JD",
    showInReview: true,
    agentContextLabel: "jd_awareness",
  },
];

const questionConfigById = new Map<PreScreenQuestionId, PreScreenQuestionConfig>(
  PRE_SCREEN_QUESTION_CONFIGS.map((question) => [question.id, question]),
);

export function getPreScreenQuestionConfig(questionId: PreScreenQuestionId) {
  return questionConfigById.get(questionId) ?? null;
}
