/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileCreatedRouteImport } from './routes/profile-created'
import { Route as PreScreeningRouteImport } from './routes/pre-screening'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticRouteImport } from './routes/diagnostic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreScreeningIndexRouteImport } from './routes/pre-screening.index'
import { Route as ApiWebhooksLivekitRouteImport } from './routes/api/webhooks/livekit'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiLivekitPreScreeningRouteImport } from './routes/api/livekit/pre-screening'
import { Route as ApiLivekitDiagnosticRouteImport } from './routes/api/livekit/diagnostic'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLivekitPreScreeningSessionIdRouteImport } from './routes/api/livekit/pre-screening.$sessionId'
import { Route as ApiLivekitPreScreeningSessionIdRetryEvaluationRouteImport } from './routes/api/livekit/pre-screening.$sessionId.retry-evaluation'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCreatedRoute = ProfileCreatedRouteImport.update({
  id: '/profile-created',
  path: '/profile-created',
  getParentRoute: () => rootRouteImport,
} as any)
const PreScreeningRoute = PreScreeningRouteImport.update({
  id: '/pre-screening',
  path: '/pre-screening',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticRoute = DiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreScreeningIndexRoute = PreScreeningIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PreScreeningRoute,
} as any)
const ApiWebhooksLivekitRoute = ApiWebhooksLivekitRouteImport.update({
  id: '/api/webhooks/livekit',
  path: '/api/webhooks/livekit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitPreScreeningRoute = ApiLivekitPreScreeningRouteImport.update({
  id: '/api/livekit/pre-screening',
  path: '/api/livekit/pre-screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitDiagnosticRoute = ApiLivekitDiagnosticRouteImport.update({
  id: '/api/livekit/diagnostic',
  path: '/api/livekit/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitPreScreeningSessionIdRoute =
  ApiLivekitPreScreeningSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => ApiLivekitPreScreeningRoute,
  } as any)
const ApiLivekitPreScreeningSessionIdRetryEvaluationRoute =
  ApiLivekitPreScreeningSessionIdRetryEvaluationRouteImport.update({
    id: '/retry-evaluation',
    path: '/retry-evaluation',
    getParentRoute: () => ApiLivekitPreScreeningSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-screening': typeof PreScreeningRouteWithChildren
  '/profile-created': typeof ProfileCreatedRoute
  '/register': typeof RegisterRoute
  '/pre-screening/': typeof PreScreeningIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/diagnostic': typeof ApiLivekitDiagnosticRoute
  '/api/livekit/pre-screening': typeof ApiLivekitPreScreeningRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
  '/api/livekit/pre-screening/$sessionId': typeof ApiLivekitPreScreeningSessionIdRouteWithChildren
  '/api/livekit/pre-screening/$sessionId/retry-evaluation': typeof ApiLivekitPreScreeningSessionIdRetryEvaluationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile-created': typeof ProfileCreatedRoute
  '/register': typeof RegisterRoute
  '/pre-screening': typeof PreScreeningIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/diagnostic': typeof ApiLivekitDiagnosticRoute
  '/api/livekit/pre-screening': typeof ApiLivekitPreScreeningRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
  '/api/livekit/pre-screening/$sessionId': typeof ApiLivekitPreScreeningSessionIdRouteWithChildren
  '/api/livekit/pre-screening/$sessionId/retry-evaluation': typeof ApiLivekitPreScreeningSessionIdRetryEvaluationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostic': typeof DiagnosticRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pre-screening': typeof PreScreeningRouteWithChildren
  '/profile-created': typeof ProfileCreatedRoute
  '/register': typeof RegisterRoute
  '/pre-screening/': typeof PreScreeningIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/livekit/diagnostic': typeof ApiLivekitDiagnosticRoute
  '/api/livekit/pre-screening': typeof ApiLivekitPreScreeningRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/livekit': typeof ApiWebhooksLivekitRoute
  '/api/livekit/pre-screening/$sessionId': typeof ApiLivekitPreScreeningSessionIdRouteWithChildren
  '/api/livekit/pre-screening/$sessionId/retry-evaluation': typeof ApiLivekitPreScreeningSessionIdRetryEvaluationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostic'
    | '/login'
    | '/onboarding'
    | '/pre-screening'
    | '/profile-created'
    | '/register'
    | '/pre-screening/'
    | '/api/auth/$'
    | '/api/livekit/diagnostic'
    | '/api/livekit/pre-screening'
    | '/api/trpc/$'
    | '/api/webhooks/livekit'
    | '/api/livekit/pre-screening/$sessionId'
    | '/api/livekit/pre-screening/$sessionId/retry-evaluation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostic'
    | '/login'
    | '/onboarding'
    | '/profile-created'
    | '/register'
    | '/pre-screening'
    | '/api/auth/$'
    | '/api/livekit/diagnostic'
    | '/api/livekit/pre-screening'
    | '/api/trpc/$'
    | '/api/webhooks/livekit'
    | '/api/livekit/pre-screening/$sessionId'
    | '/api/livekit/pre-screening/$sessionId/retry-evaluation'
  id:
    | '__root__'
    | '/'
    | '/diagnostic'
    | '/login'
    | '/onboarding'
    | '/pre-screening'
    | '/profile-created'
    | '/register'
    | '/pre-screening/'
    | '/api/auth/$'
    | '/api/livekit/diagnostic'
    | '/api/livekit/pre-screening'
    | '/api/trpc/$'
    | '/api/webhooks/livekit'
    | '/api/livekit/pre-screening/$sessionId'
    | '/api/livekit/pre-screening/$sessionId/retry-evaluation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticRoute: typeof DiagnosticRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PreScreeningRoute: typeof PreScreeningRouteWithChildren
  ProfileCreatedRoute: typeof ProfileCreatedRoute
  RegisterRoute: typeof RegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLivekitDiagnosticRoute: typeof ApiLivekitDiagnosticRoute
  ApiLivekitPreScreeningRoute: typeof ApiLivekitPreScreeningRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksLivekitRoute: typeof ApiWebhooksLivekitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-created': {
      id: '/profile-created'
      path: '/profile-created'
      fullPath: '/profile-created'
      preLoaderRoute: typeof ProfileCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-screening': {
      id: '/pre-screening'
      path: '/pre-screening'
      fullPath: '/pre-screening'
      preLoaderRoute: typeof PreScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostic': {
      id: '/diagnostic'
      path: '/diagnostic'
      fullPath: '/diagnostic'
      preLoaderRoute: typeof DiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-screening/': {
      id: '/pre-screening/'
      path: '/'
      fullPath: '/pre-screening/'
      preLoaderRoute: typeof PreScreeningIndexRouteImport
      parentRoute: typeof PreScreeningRoute
    }
    '/api/webhooks/livekit': {
      id: '/api/webhooks/livekit'
      path: '/api/webhooks/livekit'
      fullPath: '/api/webhooks/livekit'
      preLoaderRoute: typeof ApiWebhooksLivekitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit/pre-screening': {
      id: '/api/livekit/pre-screening'
      path: '/api/livekit/pre-screening'
      fullPath: '/api/livekit/pre-screening'
      preLoaderRoute: typeof ApiLivekitPreScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit/diagnostic': {
      id: '/api/livekit/diagnostic'
      path: '/api/livekit/diagnostic'
      fullPath: '/api/livekit/diagnostic'
      preLoaderRoute: typeof ApiLivekitDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit/pre-screening/$sessionId': {
      id: '/api/livekit/pre-screening/$sessionId'
      path: '/$sessionId'
      fullPath: '/api/livekit/pre-screening/$sessionId'
      preLoaderRoute: typeof ApiLivekitPreScreeningSessionIdRouteImport
      parentRoute: typeof ApiLivekitPreScreeningRoute
    }
    '/api/livekit/pre-screening/$sessionId/retry-evaluation': {
      id: '/api/livekit/pre-screening/$sessionId/retry-evaluation'
      path: '/retry-evaluation'
      fullPath: '/api/livekit/pre-screening/$sessionId/retry-evaluation'
      preLoaderRoute: typeof ApiLivekitPreScreeningSessionIdRetryEvaluationRouteImport
      parentRoute: typeof ApiLivekitPreScreeningSessionIdRoute
    }
  }
}

interface PreScreeningRouteChildren {
  PreScreeningIndexRoute: typeof PreScreeningIndexRoute
}

const PreScreeningRouteChildren: PreScreeningRouteChildren = {
  PreScreeningIndexRoute: PreScreeningIndexRoute,
}

const PreScreeningRouteWithChildren = PreScreeningRoute._addFileChildren(
  PreScreeningRouteChildren,
)

interface ApiLivekitPreScreeningSessionIdRouteChildren {
  ApiLivekitPreScreeningSessionIdRetryEvaluationRoute: typeof ApiLivekitPreScreeningSessionIdRetryEvaluationRoute
}

const ApiLivekitPreScreeningSessionIdRouteChildren: ApiLivekitPreScreeningSessionIdRouteChildren =
  {
    ApiLivekitPreScreeningSessionIdRetryEvaluationRoute:
      ApiLivekitPreScreeningSessionIdRetryEvaluationRoute,
  }

const ApiLivekitPreScreeningSessionIdRouteWithChildren =
  ApiLivekitPreScreeningSessionIdRoute._addFileChildren(
    ApiLivekitPreScreeningSessionIdRouteChildren,
  )

interface ApiLivekitPreScreeningRouteChildren {
  ApiLivekitPreScreeningSessionIdRoute: typeof ApiLivekitPreScreeningSessionIdRouteWithChildren
}

const ApiLivekitPreScreeningRouteChildren: ApiLivekitPreScreeningRouteChildren =
  {
    ApiLivekitPreScreeningSessionIdRoute:
      ApiLivekitPreScreeningSessionIdRouteWithChildren,
  }

const ApiLivekitPreScreeningRouteWithChildren =
  ApiLivekitPreScreeningRoute._addFileChildren(
    ApiLivekitPreScreeningRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticRoute: DiagnosticRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PreScreeningRoute: PreScreeningRouteWithChildren,
  ProfileCreatedRoute: ProfileCreatedRoute,
  RegisterRoute: RegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLivekitDiagnosticRoute: ApiLivekitDiagnosticRoute,
  ApiLivekitPreScreeningRoute: ApiLivekitPreScreeningRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksLivekitRoute: ApiWebhooksLivekitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
